"use client";
import Link from "next/link";
import {FormEvent,useEffect,useState} from "react";
import {useRouter} from "next/navigation";
import {createClient} from "../../lib/supabase/client";
import {authMessage} from "../../lib/auth/messages";
export default function RestablecerContrasena(){
  const router=useRouter(); const [password,setPassword]=useState(""); const [confirm,setConfirm]=useState(""); const [busy,setBusy]=useState(false); const [ready,setReady]=useState(false); const [checking,setChecking]=useState(true); const [error,setError]=useState("");
  useEffect(()=>{const supabase=createClient();supabase.auth.getSession().then(({data})=>{setReady(Boolean(data.session));setChecking(false);});const {data:{subscription}}=supabase.auth.onAuthStateChange((event)=>{if(event==="PASSWORD_RECOVERY"||event==="SIGNED_IN")setReady(true);setChecking(false);});return()=>subscription.unsubscribe();},[]);
  async function submit(e:FormEvent){e.preventDefault();setError("");if(password.length<8){setError("La contraseña debe tener al menos 8 caracteres.");return;}if(password!==confirm){setError("Las contraseñas no coinciden.");return;}setBusy(true);const supabase=createClient();const {error}=await supabase.auth.updateUser({password});setBusy(false);if(error){setError(authMessage(error,"No fue posible actualizar la contraseña."));return;}await supabase.auth.signOut();router.replace("/login?password=updated");router.refresh();}
  return <main className="auth-page"><section className="auth-compact-card"><Link href="/" className="auth-compact-brand"><span>IP</span><div><strong>InvitaPro</strong><small>Protege tu cuenta</small></div></Link><div className="auth-heading"><p className="eyebrow">Nueva contraseña</p><h1>Restablece tu acceso</h1><p>Crea una contraseña nueva para tu cuenta.</p></div>{checking?<p className="auth-helper-card">Validando tu enlace…</p>:!ready?<div className="auth-helper-card"><p>Este enlace no es válido o ya expiró.</p><Link href="/recuperar-contrasena"><strong>Solicitar un enlace nuevo</strong></Link></div>:<form className="auth-form" onSubmit={submit}><label><span>Nueva contraseña</span><input type="password" required minLength={8} autoComplete="new-password" value={password} onChange={e=>setPassword(e.target.value)} placeholder="Mínimo 8 caracteres"/></label><label><span>Confirmar contraseña</span><input type="password" required minLength={8} autoComplete="new-password" value={confirm} onChange={e=>setConfirm(e.target.value)} placeholder="Repite tu contraseña"/></label>{error&&<p className="form-error auth-error">{error}</p>}<button className="auth-submit" disabled={busy}>{busy?"Guardando…":"Guardar nueva contraseña"}<span>→</span></button></form>}<p className="auth-compact-footer"><Link href="/login"><strong>← Volver a iniciar sesión</strong></Link></p></section></main>;
}
