"use client";
import {FormEvent,useEffect,useState} from "react";
import {useRouter} from "next/navigation";
import {createClient} from "../../lib/supabase/client";
export default function RestablecerContrasena(){
  const router=useRouter(); const [password,setPassword]=useState(""); const [confirm,setConfirm]=useState(""); const [busy,setBusy]=useState(false); const [ready,setReady]=useState(false); const [error,setError]=useState("");
  useEffect(()=>{const supabase=createClient();supabase.auth.getSession().then(({data})=>setReady(Boolean(data.session)));const {data:{subscription}}=supabase.auth.onAuthStateChange((event)=>{if(event==="PASSWORD_RECOVERY"||event==="SIGNED_IN")setReady(true);});return()=>subscription.unsubscribe();},[]);
  async function submit(e:FormEvent){e.preventDefault();setError("");if(password.length<8){setError("La contraseña debe tener al menos 8 caracteres.");return;}if(password!==confirm){setError("Las contraseñas no coinciden.");return;}setBusy(true);const supabase=createClient();const {error}=await supabase.auth.updateUser({password});setBusy(false);if(error){setError(error.message);return;}await supabase.auth.signOut();router.replace("/login?password=updated");}
  return <main className="login-page"><section className="login-card"><div className="login-brand"><span>IP</span><div><strong>InvitaPro</strong><small>Protege tu cuenta</small></div></div><div className="login-heading"><p className="eyebrow">Nueva contraseña</p><h1>Restablece tu acceso</h1><p>Crea una contraseña nueva para tu cuenta.</p></div>{!ready?<p style={{lineHeight:1.6}}>Abre esta página desde el enlace que recibiste por correo. Si el enlace expiró, solicita uno nuevo desde “¿Olvidaste tu contraseña?”.</p>:<form className="login-form" onSubmit={submit}><label>Nueva contraseña<input type="password" required minLength={8} value={password} onChange={e=>setPassword(e.target.value)} placeholder="Mínimo 8 caracteres"/></label><label>Confirmar contraseña<input type="password" required minLength={8} value={confirm} onChange={e=>setConfirm(e.target.value)} placeholder="Repite tu contraseña"/></label>{error&&<p className="form-error">{error}</p>}<button className="button button-primary login-button" disabled={busy}>{busy?"Guardando…":"Guardar nueva contraseña"}</button></form>}</section></main>;
}