'use client';
import Link from 'next/link';
import { useEffect, useMemo, useState } from 'react';
import { createClient } from '@/lib/supabase/client';
import { Confirmacion, Evento, formatDate, Invitacion, Invitado, Cliente, messageFromError } from '@/lib/invitapro';
import { ArrowRightIcon, CalendarIcon, CheckCircleIcon, ClientIcon, EyeIcon, InvitationIcon, PeopleIcon, TicketIcon } from '@/components/admin/dashboard-icons';
function relativeTime(value:string){const m=Math.max(0,Math.floor((Date.now()-new Date(value).getTime())/60000));if(m<1)return'ahora';if(m<60)return`hace ${m} min`;const h=Math.floor(m/60);return h<24?`hace ${h} h`:`hace ${Math.floor(h/24)} días`}
export default function AdminPage(){const supabase=useMemo(()=>createClient(),[]);const[clientes,setClientes]=useState<Cliente[]>([]);const[eventos,setEventos]=useState<Evento[]>([]);const[invitaciones,setInvitaciones]=useState<Invitacion[]>([]);const[invitados,setInvitados]=useState<Invitado[]>([]);const[confirmaciones,setConfirmaciones]=useState<Confirmacion[]>([]);const[loading,setLoading]=useState(true);const[error,setError]=useState('');
async function load(){setLoading(true);const[c,e,i,g,r]=await Promise.all([supabase.from('clientes').select('*'),supabase.from('eventos').select('*'),supabase.from('invitaciones').select('*, eventos(id,nombre,tipo,fecha,hora,lugar,direccion,maps_url,cliente_id,clientes(id,nombre))').order('created_at',{ascending:false}),supabase.from('invitados').select('*'),supabase.from('confirmaciones').select('*, invitados(nombre,codigo), invitaciones(titulo,slug)').order('updated_at',{ascending:false})]);for(const x of[c,e,i,g,r])if(x.error)setError(messageFromError(x.error));setClientes((c.data??[]) as Cliente[]);setEventos((e.data??[]) as Evento[]);setInvitaciones((i.data??[]) as Invitacion[]);setInvitados((g.data??[]) as Invitado[]);setConfirmaciones((r.data??[]) as Confirmacion[]);setLoading(false)}useEffect(()=>{void load();const ch=supabase.channel('dashboard-live').on('postgres_changes',{event:'*',schema:'public',table:'confirmaciones'},()=>void load()).on('postgres_changes',{event:'*',schema:'public',table:'invitaciones'},()=>void load()).subscribe();return()=>{void supabase.removeChannel(ch)}},[]);
if(loading)return <div className="dashboard-loading">Preparando dashboard…</div>;const published=invitaciones.filter(x=>x.estado==='publicada').length;const yes=confirmaciones.filter(x=>x.asistira);const confirmedPeople=yes.reduce((s,x)=>s+x.adultos+x.ninos,0);const passes=invitados.reduce((s,x)=>s+x.adultos_permitidos+x.ninos_permitidos,0);const pending=Math.max(invitados.length-confirmaciones.filter(x=>x.invitado_id).length,0);const rate=invitados.length?Math.round((confirmaciones.filter(x=>x.invitado_id).length/invitados.length)*100):0;
return <div className="page-stack dashboard-premium">
<section className="page-heading dashboard-heading"><div><p className="eyebrow">Resumen general</p><h1>Dashboard</h1><p>Consulta el estado general de clientes, eventos e invitaciones.</p></div><Link href="/admin/invitaciones" className="button button-primary">Crear invitación</Link></section>
<section className="stats-grid dashboard-live-stats">
<Link href="/admin/invitaciones" className="stat-card dashboard-stat-card"><span className="dashboard-stat-icon"><InvitationIcon/></span><div><span>Invitaciones activas</span><strong>{published}</strong><small>{invitaciones.length} registradas</small></div><ArrowRightIcon className="dashboard-stat-arrow"/></Link>
<Link href="/admin/confirmaciones" className="stat-card dashboard-stat-card"><span className="dashboard-stat-icon"><PeopleIcon/></span><div><span>Personas confirmadas</span><strong>{confirmedPeople}</strong><small>De {passes} pases asignados</small></div><ArrowRightIcon className="dashboard-stat-arrow"/></Link>
<Link href="/admin/confirmaciones" className="stat-card dashboard-stat-card"><span className="dashboard-stat-icon"><CheckCircleIcon/></span><div><span>Respuestas</span><strong>{confirmaciones.length}</strong><small>{pending} pases pendientes</small></div><ArrowRightIcon className="dashboard-stat-arrow"/></Link>
<Link href="/admin/clientes" className="stat-card dashboard-stat-card"><span className="dashboard-stat-icon"><ClientIcon/></span><div><span>Clientes</span><strong>{clientes.length}</strong><small>{eventos.length} eventos</small></div><ArrowRightIcon className="dashboard-stat-arrow"/></Link>
</section>
<section className="dashboard-progress-grid"><article className="panel-card confirmation-progress-card"><div className="panel-header"><div><h2>Avance RSVP</h2><p>Respuestas de pases personalizados.</p></div><strong className="progress-percentage">{rate}%</strong></div><div className="progress-track"><span style={{width:`${rate}%`}}/></div><div className="progress-legend"><span><i className="legend-dot confirmed"/>{yes.length} sí</span><span><i className="legend-dot declined"/>{confirmaciones.filter(x=>!x.asistira).length} no</span><span><i className="legend-dot pending"/>{pending} pendientes</span></div></article>
<article className="panel-card quick-actions-card"><div className="panel-header"><div><h2>Acciones rápidas</h2><p>Accesos frecuentes del panel.</p></div></div><div className="quick-action-grid dashboard-quick-actions"><Link href="/admin/clientes"><ClientIcon/><strong>Clientes</strong><small>Altas y cambios</small></Link><Link href="/admin/eventos"><CalendarIcon/><strong>Eventos</strong><small>Fechas y lugares</small></Link><Link href="/admin/invitados"><TicketIcon/><strong>Invitados</strong><small>Pases privados</small></Link><Link href="/admin/confirmaciones"><CheckCircleIcon/><strong>Confirmaciones</strong><small>Respuestas en vivo</small></Link></div></article></section>
<section className="dashboard-grid"><article className="panel-card panel-card-wide"><div className="panel-header"><div><h2>Invitaciones recientes</h2><p>Últimas invitaciones creadas.</p></div><Link href="/admin/invitaciones" className="text-link">Ver todas</Link></div><div className="table-wrap"><table className="data-table dashboard-recent-table"><thead><tr><th>Invitación</th><th>Tipo</th><th>Fecha</th><th>Estado</th><th>Acción</th></tr></thead><tbody>{invitaciones.slice(0,5).map(x=><tr key={x.id}><td><strong>{x.titulo}</strong><span>{x.slug}</span></td><td>{x.eventos?.tipo||x.modalidad}</td><td>{formatDate(x.eventos?.fecha)}</td><td><span className={`badge ${x.estado==='publicada'?'badge-success':'badge-neutral'}`}>{x.estado}</span></td><td><Link className="dashboard-preview-link" href={`/invitacion/${x.slug}?preview=1`} target="_blank"><EyeIcon/>Vista previa</Link></td></tr>)}</tbody></table></div></article>
<article className="panel-card activity-live-card"><div className="panel-header"><div><h2>Actividad RSVP</h2><p>Tiempo real.</p></div></div><div className="activity-list live-activity-list">{confirmaciones.slice(0,6).map(x=>{const name=x.invitados?.nombre||x.nombre||'Invitado';return <div key={x.id}><span className={`activity-icon ${x.asistira?'success':'declined'}`}>{x.asistira?'✓':'×'}</span><p><strong>{name} {x.asistira?'confirmó':'no asistirá'}</strong><small>{x.invitaciones?.titulo||'Invitación'} · {x.adultos+x.ninos} persona(s)</small><em>{relativeTime(x.updated_at)}</em></p></div>})}{!confirmaciones.length&&<div className="activity-empty"><span>✓</span><p><strong>Esperando respuestas</strong><small>Aparecerán automáticamente.</small></p></div>}</div></article></section>{error&&<p className="form-error">{error}</p>}</div>}
