'use client';
import {useCallback,useEffect,useMemo,useState} from 'react';
import {createClient} from '@/lib/supabase/client';

type Invite={id:string;titulo:string;slug:string;eventos:{nombre:string}|{nombre:string}[]|null};
type Photo={id:string;invitacion_id:string;storage_path:string;nombre_archivo:string|null;autor_nombre:string|null;estado:'pendiente'|'aprobada'|'rechazada';portada:boolean;created_at:string;url?:string};

export default function AdminAlbumPage(){
 const supabase=useMemo(()=>createClient(),[]);const[invites,setInvites]=useState<Invite[]>([]);const[selected,setSelected]=useState('');const[photos,setPhotos]=useState<Photo[]>([]);const[status,setStatus]=useState('pendiente');const[loading,setLoading]=useState(true);const[error,setError]=useState('');
 const loadInvites=useCallback(async()=>{const{data,error}=await supabase.from('invitaciones').select('id,titulo,slug,eventos(nombre)').order('created_at',{ascending:false});if(error){setError(error.message);setLoading(false);return}const rows=(data||[]) as Invite[];setInvites(rows);setSelected(x=>x||rows[0]?.id||'');setLoading(false)},[supabase]);
 const loadPhotos=useCallback(async(invitationId:string)=>{if(!invitationId){setPhotos([]);return}setLoading(true);const{data,error}=await supabase.from('album_colaborativo_fotos').select('id,invitacion_id,storage_path,nombre_archivo,autor_nombre,estado,portada,created_at').eq('invitacion_id',invitationId).order('created_at',{ascending:false});if(error){setError(error.message);setLoading(false);return}const rows=(data||[]) as Photo[];const hydrated=await Promise.all(rows.map(async p=>{const{data:signed}=await supabase.storage.from('guest-album').createSignedUrl(p.storage_path,3600);return{...p,url:signed?.signedUrl}}));setPhotos(hydrated);setLoading(false)},[supabase]);
 useEffect(()=>{const timer=window.setTimeout(()=>{void loadInvites()},0);return()=>window.clearTimeout(timer)},[loadInvites]);useEffect(()=>{const timer=window.setTimeout(()=>{void loadPhotos(selected)},0);return()=>window.clearTimeout(timer)},[loadPhotos,selected]);
 async function moderate(photo:Photo,next:'pendiente'|'aprobada'|'rechazada',cover=false){setError('');const{error}=await supabase.rpc('moderar_foto_album',{p_foto_id:photo.id,p_estado:next,p_portada:cover});if(error){setError(error.message);return}await loadPhotos(selected)}
 async function remove(photo:Photo){if(!confirm('¿Eliminar esta fotografía de forma permanente?'))return;const storage=await supabase.storage.from('guest-album').remove([photo.storage_path]);if(storage.error){setError(storage.error.message);return}const{error}=await supabase.from('album_colaborativo_fotos').delete().eq('id',photo.id);if(error)setError(error.message);else await loadPhotos(selected)}
 const visible=photos.filter(p=>status==='todas'||p.estado===status);const counts={pendiente:photos.filter(p=>p.estado==='pendiente').length,aprobada:photos.filter(p=>p.estado==='aprobada').length,rechazada:photos.filter(p=>p.estado==='rechazada').length};
 return <section className="album-admin-page"><div className="panel-header album-page-heading"><div><p className="eyebrow">Álbum inteligente</p><h1>Moderación de fotografías</h1><p>Revisa las imágenes compartidas por los invitados antes de mostrarlas.</p></div><label>Invitación<select value={selected} onChange={e=>setSelected(e.target.value)}>{invites.map(i=>{const ev=Array.isArray(i.eventos)?i.eventos[0]:i.eventos;return <option key={i.id} value={i.id}>{ev?.nombre||i.titulo}</option>})}</select></label></div>{error&&<div className="error-banner">{error}</div>}<div className="album-summary-grid"><button onClick={()=>setStatus('pendiente')} className={status==='pendiente'?'active':''}><strong>{counts.pendiente}</strong><span>Pendientes</span></button><button onClick={()=>setStatus('aprobada')} className={status==='aprobada'?'active':''}><strong>{counts.aprobada}</strong><span>Aprobadas</span></button><button onClick={()=>setStatus('rechazada')} className={status==='rechazada'?'active':''}><strong>{counts.rechazada}</strong><span>Rechazadas</span></button><button onClick={()=>setStatus('todas')} className={status==='todas'?'active':''}><strong>{photos.length}</strong><span>Total</span></button></div>{loading?<div className="empty-state">Cargando fotografías…</div>:visible.length?<div className="album-photo-grid">{visible.map(photo=><article key={photo.id} className="album-photo-card"><div className="album-photo-preview">{photo.url?<img src={photo.url} alt={photo.nombre_archivo||'Foto del evento'}/>:<span>Sin vista previa</span>}{photo.portada&&<b>Portada</b>}</div><div className="album-photo-info"><strong>{photo.autor_nombre||'Invitado anónimo'}</strong><small>{new Date(photo.created_at).toLocaleString('es-MX')}</small><span className={`album-status status-${photo.estado}`}>{photo.estado}</span></div><div className="album-photo-actions"><button onClick={()=>moderate(photo,'aprobada',false)}>Aprobar</button><button onClick={()=>moderate(photo,'aprobada',true)}>Portada</button><button onClick={()=>moderate(photo,'rechazada',false)}>Rechazar</button><button className="danger" onClick={()=>remove(photo)}>Eliminar</button></div></article>)}</div>:<div className="empty-state"><strong>No hay fotografías en este estado</strong><span>Las nuevas imágenes aparecerán aquí para moderación.</span></div>}</section>
}
