import type { ThemeDefinition } from "@/lib/themes/theme-types";

export const THEME_REGISTRY: ThemeDefinition[] = [
  {id:"elegant-classic",name:"Elegant Classic",collection:"Wedding",description:"Marfil, café cálido y serif editorial.",palette:{primary:"#9a6845",secondary:"#d8c3aa",background:"#fbf7f1",surface:"#ffffff",text:"#33271f",muted:"#77685c"},typography:{heading:'Georgia, "Times New Roman", serif',body:'Inter, Arial, sans-serif'},buttonStyle:"solid",radius:"soft",motion:"soft",spacing:{section:"72px",card:"24px"},shadow:"0 18px 50px rgba(63,42,27,.12)"},
  {id:"luxury-black",name:"Luxury Black",collection:"Wedding",description:"Negro profundo con acentos dorados.",palette:{primary:"#c7a55b",secondary:"#6f5a2e",background:"#0d0d0d",surface:"#171717",text:"#f8f1df",muted:"#b9ad94"},typography:{heading:'Georgia, "Times New Roman", serif',body:'Inter, Arial, sans-serif'},buttonStyle:"outline",radius:"square",motion:"cinematic",spacing:{section:"88px",card:"28px"},shadow:"0 26px 70px rgba(0,0,0,.42)"},
  {id:"romantic-garden",name:"Romantic Garden",collection:"Wedding",description:"Verdes botánicos y tonos naturales.",palette:{primary:"#7f9a78",secondary:"#d6c8ad",background:"#f6f4ec",surface:"#fffdf8",text:"#344333",muted:"#758071"},typography:{heading:'Georgia, "Times New Roman", serif',body:'Inter, Arial, sans-serif'},buttonStyle:"soft",radius:"rounded",motion:"soft",spacing:{section:"76px",card:"24px"},shadow:"0 20px 54px rgba(78,96,67,.14)"},
  {id:"editorial-ivory",name:"Editorial Ivory",collection:"Wedding",description:"Blanco editorial con contraste tipográfico.",palette:{primary:"#8a7158",secondary:"#ddd0c1",background:"#f8f5ef",surface:"#fffdf9",text:"#27231f",muted:"#766f67"},typography:{heading:'"Times New Roman", Georgia, serif',body:'Inter, Arial, sans-serif'},buttonStyle:"outline",radius:"square",motion:"minimal",spacing:{section:"96px",card:"20px"},shadow:"0 16px 40px rgba(45,38,30,.08)"},
  {id:"princess-rose",name:"Princess Rose",collection:"XV años",description:"Rosa elegante con acabado delicado.",palette:{primary:"#c78ca7",secondary:"#f0cddd",background:"#fff4f8",surface:"#ffffff",text:"#593848",muted:"#947181"},typography:{heading:'Georgia, "Times New Roman", serif',body:'Inter, Arial, sans-serif'},buttonStyle:"solid",radius:"rounded",motion:"dynamic",spacing:{section:"76px",card:"24px"},shadow:"0 22px 56px rgba(154,88,116,.16)"},
  {id:"golden-night",name:"Golden Night",collection:"XV años",description:"Azul noche y destellos dorados.",palette:{primary:"#c2a14b",secondary:"#6b5522",background:"#111426",surface:"#1b1f35",text:"#fff5d1",muted:"#c8bc92"},typography:{heading:'Georgia, "Times New Roman", serif',body:'Inter, Arial, sans-serif'},buttonStyle:"outline",radius:"soft",motion:"cinematic",spacing:{section:"88px",card:"26px"},shadow:"0 28px 72px rgba(3,5,18,.46)"},
  {id:"dinosaurios",name:"Dinosaurios",collection:"Infantil",description:"Verde aventura con formas divertidas.",palette:{primary:"#598a64",secondary:"#b7834a",background:"#eef5e8",surface:"#ffffff",text:"#294431",muted:"#647b68"},typography:{heading:'"Trebuchet MS", Arial, sans-serif',body:'Inter, Arial, sans-serif'},buttonStyle:"solid",radius:"rounded",motion:"dynamic",spacing:{section:"64px",card:"22px"},shadow:"0 18px 44px rgba(62,91,55,.16)"},
  {id:"espacial",name:"Espacial",collection:"Infantil",description:"Universo oscuro con acentos violetas.",palette:{primary:"#7185e4",secondary:"#9d6fca",background:"#090d25",surface:"#151b3b",text:"#f3f4ff",muted:"#a8afd0"},typography:{heading:'"Trebuchet MS", Arial, sans-serif',body:'Inter, Arial, sans-serif'},buttonStyle:"soft",radius:"rounded",motion:"dynamic",spacing:{section:"72px",card:"24px"},shadow:"0 24px 64px rgba(4,7,30,.44)"},
  {id:"corporate-blue",name:"Corporate Blue",collection:"Empresarial",description:"Azul profesional, limpio y moderno.",palette:{primary:"#335d7a",secondary:"#8ca6b8",background:"#f3f6f8",surface:"#ffffff",text:"#172b38",muted:"#687c88"},typography:{heading:'Inter, Arial, sans-serif',body:'Inter, Arial, sans-serif'},buttonStyle:"solid",radius:"square",motion:"minimal",spacing:{section:"64px",card:"20px"},shadow:"0 16px 38px rgba(27,55,72,.1)"},
  {id:"campamento-bosque",name:"Bosque de Fe",collection:"Campamentos",description:"Verde bosque, crema y acento fogata.",palette:{primary:"#f08a32",secondary:"#9fc07f",background:"#102b22",surface:"#f6eddc",text:"#fff8e9",muted:"#c9d8c8"},typography:{heading:'"Trebuchet MS", Arial, sans-serif',body:'Inter, Arial, sans-serif'},buttonStyle:"solid",radius:"rounded",motion:"dynamic",spacing:{section:"72px",card:"24px"},shadow:"0 24px 64px rgba(8,34,25,.3)"},
  {id:"campamento-fogata",name:"Noche de Fogata",collection:"Campamentos",description:"Noche cálida, carbón y naranja fuego.",palette:{primary:"#f28b3c",secondary:"#f4c36c",background:"#1b1412",surface:"#30211b",text:"#fff5e7",muted:"#d8b9a2"},typography:{heading:'"Trebuchet MS", Arial, sans-serif',body:'Inter, Arial, sans-serif'},buttonStyle:"outline",radius:"soft",motion:"cinematic",spacing:{section:"78px",card:"24px"},shadow:"0 28px 70px rgba(15,6,3,.44)"},
];

export const DEFAULT_THEME_ID = "elegant-classic";

export function getThemeById(id: string | null | undefined) {
  return THEME_REGISTRY.find((theme) => theme.id === id) || THEME_REGISTRY.find((theme) => theme.id === DEFAULT_THEME_ID)!;
}
