'use client';
import { useEffect, useMemo, useState } from 'react';
import { createClient } from '@/lib/supabase/client';
import { Confirmacion, initials, messageFromError } from '@/lib/invitapro';
export default function ConfirmacionesPage(){const supabase=useMemo(()=>createClient(),[]);const[items,setItems]=useState<Confirmacion[]>([]);const[loading,setLoading]=useState(true);const[search,setSearch]=useState('');const[filter,setFilter]=useState('todas');const[deleting,setDeleting]=useState<Confirmacion|null>(null);const[error,setError]=useState('');
async function load(){setLoading(true);const r=await supabase.from('confirmaciones').select('*, invitados(nombre,codigo), invitaciones(titulo,slug)').order('updated_at',{ascending:false});if(r.error)setError(messageFromError(r.error));else setItems((r.data??[]) as Confirmacion[]);setLoading(false)}useEffect(()=>{void load();const channel=supabase.channel('admin-confirmaciones').on('postgres_changes',{event:'*',schema:'public',table:'confirmaciones'},()=>void load()).subscribe();return()=>{void supabase.removeChannel(channel)}},[]);
async function remove(){if(!deleting)return;const r=await supabase.from('confirmaciones').delete().eq('id',deleting.id);if(r.error)setError(messageFromError(r.error));setDeleting(null);await load()}
const list=useMemo(()=>items.filter(x=>filter==='todas'||(filter==='si'?x.asistira:!x.asistira)).filter(x=>[x.nombre,x.invitados?.nombre,x.invitados?.codigo,x.invitaciones?.titulo,x.mensaje].join(' ').toLowerCase().includes(search.toLowerCase().trim())),[items,filter,search]);const yes=items.filter(x=>x.asistira);const people=yes.reduce((s,x)=>s+x.adultos+x.ninos,0);
return <div className="page-stack"><section className="page-heading"><div><p className="eyebrow">RSVP</p><h1>Confirmaciones</h1><p>Esta pantalla se actualiza en tiempo real desde Supabase.</p></div></section><section className="stats-grid confirmation-stats"><article className="stat-card"><span>Respuestas</span><strong>{items.length}</strong><small>Recibidas</small></article><article className="stat-card"><span>Personas confirmadas</span><strong>{people}</strong><small>Adultos y niños</small></article><article className="stat-card"><span>No asistirán</span><strong>{items.filter(x=>!x.asistira).length}</strong><small>Respuestas negativas</small></article></section><section className="panel-card"><div className="panel-header events-toolbar"><div><h2>Registro de respuestas</h2><p>Sin recargar la página.</p></div><div className="events-filters"><label className="search-field"><span>⌕</span><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Buscar invitado o mensaje"/></label><select className="status-filter" value={filter} onChange={e=>setFilter(e.target.value)}><option value="todas">Todas</option><option value="si">Sí asistirá</option><option value="no">No asistirá</option></select></div></div>{loading?<div className="dashboard-loading">Cargando respuestas…</div>:list.length===0?<div className="empty-state compact-empty"><div className="empty-icon">✓</div><h2>Sin respuestas</h2><p>Las confirmaciones públicas aparecerán aquí.</p></div>:<div className="table-wrap"><table className="data-table"><thead><tr><th>Invitado</th><th>Invitación</th><th>Respuesta</th><th>Asistentes</th><th>Mensaje</th><th>Fecha</th><th></th></tr></thead><tbody>{list.map(x=>{const name=x.invitados?.nombre||x.nombre||'Invitado';return <tr key={x.id}><td><div className="client-name-cell"><span className="client-avatar">{initials(name)}</span><div><strong>{name}</strong><span>{x.invitados?.codigo||'RSVP público'}</span></div></div></td><td>{x.invitaciones?.titulo||'—'}</td><td><span className={`badge ${x.asistira?'badge-success':'badge-neutral'}`}>{x.asistira?'Sí asistirá':'No asistirá'}</span></td><td>{x.asistira?`${x.adultos} adultos · ${x.ninos} niños`:'0'}</td><td>{x.mensaje||'—'}</td><td>{new Intl.DateTimeFormat('es-MX',{dateStyle:'medium',timeStyle:'short'}).format(new Date(x.updated_at))}</td><td><button className="text-button danger" onClick={()=>setDeleting(x)}>Eliminar</button></td></tr>})}</tbody></table></div>}</section>{error&&<p className="form-error">{error}</p>}{deleting&&<div className="modal-backdrop delete-backdrop"><section className="delete-modal"><div className="delete-icon">✕</div><div className="delete-heading"><h2>Eliminar respuesta</h2><p>Esta acción se reflejará en Supabase.</p></div><div className="delete-actions"><button className="button button-outline" onClick={()=>setDeleting(null)}>Cancelar</button><button className="button button-danger" onClick={remove}>Sí, eliminar</button></div></section></div>}</div>}
